### ISSUE TITLE
proposed changes to workflow

### ISSUE THREAD

**Issue by connorjclark** [cristianadam/HelloWorld#10]
Would you accept a PR that does these things:

- replace deprecated set_output/set_state with new github actions equivalent
- use `env:` yaml block instead of cmake script
- use `- run: ccache -s` instead of cmake script
- use `github.run_id` for cache instead of cmake script current time (plays nicer with job retry)
- delete download of cmake https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml#L70 - doesn't seem necessary, is what GitHub provides not good enough?

BTW: thank you _so much_ for the clear article and example code here, it's been so useful.

**Comment by cristianadam** [comment]
Thank you for showing interest and contributing. But I would like to keep the project as the sample project for the blog article.
