### ISSUE TITLE
Pack stage fails for all jobs

### ISSUE THREAD

**Issue by Wani4ka** [cristianadam/HelloWorld#11]
![image](https://user-images.githubusercontent.com/31739611/200729312-a39fa1ba-a088-4470-8ddc-6d8089e3352a.png)

![image](https://user-images.githubusercontent.com/31739611/200729336-28728ea2-21a8-4977-9e89-fb8bffa4ac96.png)

![image](https://user-images.githubusercontent.com/31739611/200729368-97d0ae5c-41bb-4eae-bdf9-7cc65ac12b12.png)

![image](https://user-images.githubusercontent.com/31739611/200729399-8e91a248-c5e8-4319-aa91-776dbc94dde0.png)

**Comment by cristianadam** [comment]
Might have been a GitHub Actions temporary problem. I have pushed today 3 commits and they were all fine, see https://github.com/cristianadam/HelloWorld/actions/
