### ISSUE TITLE
MSVC compiler lookup fails with windows-2022

### ISSUE THREAD

**Issue by acmnpv** [cristianadam/HelloWorld#6]
Hello,

we are using the basic build script here to run our post merge testing on MSVC for https://github.com/gromacs/gromacs and it is been working fine.

Since the default wndows-latest environment changed to windows-2022, the compiler lookup fails (see here for an example failing build: https://github.com/gromacs/gromacs/runs/5229802627?check_suite_focus=true). I just wanted to let you know about the issue in case you are planning to update the files here.

Thanks for the helpful tool!

Cheers

Paul

**Comment by cristianadam** [comment]
Fixed by 363fa28c7a003627f3539d12fd31fc03289b9b94
