### ISSUE TITLE
Caching is not working on CI

### ISSUE THREAD

**Issue by ylz-at** [cristianadam/HelloWorld#8]
```
Cache not found for input keys: Windows Latest MSVC-ccache-2022-04-07-14;27;45, Windows Latest MSVC-ccache-
```

**Comment by cristianadam** [comment]
This is known to happen from time to time. If I remember correctly the cache is valid for a week, so it could happen that a commit after a week could not have the cache anymore.

I pushed a few commits today and:
1. the first commit after seven months was not fine https://github.com/cristianadam/HelloWorld/actions/runs/3446989554
2. the latest commit https://github.com/cristianadam/HelloWorld/actions/runs/3447484851 was fine
